print("hello welcome to name list")
print(" what's your name?")
a = input()
print("Hw old are u?")
b = input()
print("where do u came from?")
c = input()
print(f"I'm {a} , i am {b} years old \n i came from {c}")
text = '"you are Karaneh user"'
print(text)